
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY products.py .
COPY . .
#COPY templates/products.html /app/templates/

CMD ["python", "products.py"]

